var consts = require('./const.js');
var Upstox = require("upstox");
var upstox = new Upstox(consts.upstox.API_KEY);

upstox.setToken(consts.upstox.ACCESS_TOKEN);

//symbolsFnO = "ZEEL,YESBANK,WOCKPHARMA,WIPRO,VOLTAS,VEDL,UPL,UNIONBANK,ULTRACEMCO,UJJIVAN,UBL,TVSMOTOR,TV18BRDCST,TORNTPOWER,TORNTPHARM,TITAN,TECHM,TCS,TATASTEEL,TATAPOWER,TATAMTRDVR,TATAMOTORS,TATAGLOBAL,TATAELXSI,TATACOMM,TATACHEM,SYNDIBANK,SUZLON,SUNTV,SUNPHARMA,STAR,SRTRANSFIN,SRF,SOUTHBANK,SINTEX,SIEMENS,SHREECEM,SBIN,SAIL,RPOWER,RELINFRA,RELIANCE,RELCAPITAL,RECLTD,RDEL,RCOM,PVR,PTC,POWERGRID,PNB,PIDILITIND,PFC,PETRONET,PEL,PCJEWELLER,PAGEIND,ORIENTBANK,ONGC,OIL,OFSS,NTPC,NMDC,NIITTECH,NHPC,NCC,MUTHOOTFIN,MRF,MOTHERSUMI,MINDTREE,MFSL,MCDOWELL-N,MARUTI,MARICO,M&MFIN,M&M,LUPIN,LT,LICHSGFIN,L&TFH,KTKBANK,KSCL,KPIT,KOTAKBANK,JUSTDIAL,JUBLFOOD,JSWSTEEL,JSWENERGY,JPASSOCIAT,JISLJALEQS,JINDALSTEL,JETAIRWAYS,ITC,IRB,IOC,INFY,INFRATEL,INFIBEAM,INDUSINDBK,INDIGO,INDIANB,INDIACEM,IGL,IFCI,IDFCBANK,IDFC,IDEA,IDBI,ICIL,ICICIBANK,IBULHSGFIN,IBREALEST,HINDZINC,HINDUNILVR,HINDPETRO,HINDALCO,HEXAWARE,HEROMOTOCO,HDIL,HDFCBANK,HDFC,HCLTECH,HAVELLS,GRASIM,GRANULES,GODREJIND,GODREJCP,GMRINFRA,GLENMARK,GAIL,FEDERALBNK,EXIDEIND,ESCORTS,EQUITAS,ENGINERSIN,DRREDDY,DLF,DIVISLAB,DISHTV,DHFL,DCBBANK,DALMIABHA,DABUR,CUMMINSIND,CONCOR,COLPAL,COALINDIA,CIPLA,CGPOWER,CESC,CENTURYTEX,CEATLTD,CASTROLIND,CAPF,CANBK,CADILAHC,BRITANNIA,BPCL,BIOCON,BHEL,BHARTIARTL,BHARATFORG,BHARATFIN,BEML,BEL,BATAINDIA,BANKINDIA,BANKBARODA,BAJFINANCE,BAJAJ-AUTO,AXISBANK,AUROPHARMA,ASIANPAINT,ASHOKLEY,ARVIND,APOLLOTYRE,APOLLOHOSP,ANDHRABANK,AMBUJACEM,AMARAJABAT,ALBK,AJANTPHARM,ADANIPOWER,ADANIPORTS,ADANIENT,ACC";
symbolsFnO = "ACC";
var feedSub = {
    "type": "full",
    "exchange": "nse_eq",
    "symbol": symbolsFnO
};

upstox.unsubscribeFeed(feedSub).then(function (response) {
                console.log(response);
            });